text 1
Aliens are attacking!! Slay these vermin!!!

text 2
Abandoned base spotted to the west!!!

text 3
Perta-7 is being extracted, good job!!!

text 4
Take care about continuous Petra-7 supplement

text 5
Destroy the enemy base that is hidden somewhere in this crypt!!!

text 6
Captain is dead. Mission aborted

text 7
You will be demoted!

text 8
Unfortunately it demands some kind of activation. You must go over there.

text 9
Allied units spotted in the area!!!

text 10
Get close to the lost soldiers and they will follow us!!!

text 11
Explore the vents on the west that you were crossing by.

text 12
Alien bases have been destroyed!!!

text 13
Well done, Soldier!!!

text 14
Colony has been destroyed. Mission aborted

