text 1
Welcome back on the surface.

text 2
This colony is at your disposal

text 3
Support the Ternox Corporation in the fight against the aliens.

text 4
Warning! Enemy saucer has been spotted near the colony!

text 5
Aliens are advancing to the Ternox base. Send them reinforcements.

text 6
Captain is dead. Mission aborted

text 7
You will be demoted!

text 8
Ternox colony destroyed. Mission aborted.

text 9
Alien bases are destroyed!!!

text 10
Well done!!!

text 11
Colony has been destroyed. Mission aborted.

text 12
Captain had been healed and reached the base!!!

text 13
Our scientists have localized the artifacts.

