text 1
Welcome on the Red Planet, Commander

text 2
Use the Captain to improve troop morale

text 3
We are sending you a little support

text 4
We have 3 newest robots for you

text 5
Well done, Soldier!!!

text 6
Captain is dead. Mission aborted

text 7
You will be demoted!

text 8
Ternox's Colony is destroyed. Mission aborted

text 9
Ternox's Colony localized. Destroy the incubators!!!

text 10
Incubators destroyed. Find the base!!!

