text 1
Ternox Commander is on his way!!!

text 2
Fight the enemy off till he arrives.

text 3
Find the ancient ruins

text 4
Ruins have been localized!

text 5
Well done, Soldier!!!

text 6
Captain is dead. Mission aborted

text 7
You will be demoted!

text 8
Ternox's colony is destroyed. Mission aborted

text 9
Now find the ruins!!!

text 10
Mission complete!!!

text 11
Ternox Commander has arrived!!!

