text 1
The time of revenge has come

text 2
Destroy the Ternox Headquarters

text 3
Find and eliminate Marrus and Sirmu

text 4
Mission complete!!!

text 5
Well done!!!

text 6
Captain is dead. Mission aborted!!!

text 7
You will be demoted

text 8
Captain has been healed and reached the base

text 9
Message from Ziru:

text 10
Well done, now you deserve my help

text 11
Destroy transmitters in Ternox base, and I will send you reinforcements.

text 12
Sirmu's and Marrus' bases are destroyed!!! 

text 13
Well done!!!

text 14
Colony has been destroyed. Mission aborted!!!

text 15
Destroy Ternox extracting center!!!

text 16
Message from Sirmu:

text 17
You will pay for this...

text 18
Warning! Saucer have been spotted near the colony!!!

text 19
Secure the extraction center and protect it for two days

text 20
Extraction center remains ours. Good job

text 21
Now finish Marrus and Sirmu!!!

text 22
Extraction center has been lost. Mission aborted!!!

