text 1
Move with your escort to the rendezvous point with Marrus and Sirmu

text 2
Reach the reinforcements at the west

text 3
You have reached the exit, well done!!!

text 4
Ziru was killed. You have failed!!!

text 5
Captain is dead. Mission aborted

text 6
We have lost contact with our reinforcements on the west!!!

text 7
Run, Captain, Sirmu and Marrus have betrayed us it is a tra-... Aughhh!!!!

text 8
A message from Marrus:

text 9
Localize the prison and free Ziru. He is our last hope.

text 10
You have saved my life so I will help you to leave the crypt.

text 11
Follow Ziru to the exit

text 12
Message from Ziru:

text 13
Haha, now this is your end!! You are dead now!!!

text 14
There are too many of them. You must find some way out.

