text 1
The base have been localized to the west.

text 2
Enemy units localized near the base.

text 3
You must destroy this squad.

text 4
Mission completed!!!

text 5
Well done!!!

text 6
Captain is dead. Mission aborted

text 7
You'll be demoted!!!

text 8
Captain has been healed and reached the base!!!

text 9
We are sending reinforcements!!!

text 10
Marrus is signing an alliance with rebels somewhere in the area right now

text 11
You have to find that place 

text 12
All Aliens' bases have been destroyed

text 13
Well done!!!

text 14
Colony has been destroyed. Mission aborted

text 15
We are sending some Osprey IVs in order to make a recon with them

text 16
Message from the rebels' leader, Sirmu.

text 17
Destroy the transmitters before Ziru will call the reinforcements!!!

text 18
Marrus and Sirmu have signed an alliance!!!

text 19
Secure the place before Ternox will send reinforcements!!!

text 20
Colony has been destroyed. Mission aborted

text 21
Alien's transmitters have been destroyed!!!

text 22
Ternox camp destroyed!!!

