text 1
Ziru's base is surrounded.

text 2
Localize his forces and supply point

text 3
Find and eliminate Marrus and Sirmu

text 4
Mission complete!!!

text 5
Well done!!!

text 6
Captain is dead. Mission aborted!!!

text 7
Ziru has been killed. You have failed!!!

text 8
Good job!

text 9
Reinforcements have reached their destination point

text 10
Marrus and Sirmu are esacping. Catch them, hurry up!!!

text 11
Destroy the enemy units near the base

text 12
Ziru's base destroyed. Mission aborted.

text 13
Ternox colony destroyed

text 14
They have managed to escape but this is not the end. We will catch them soon.

text 15
Destroy Ternox colonies!!!

