text 1
Destroy enemy's transmitters near 9 Exo stations!!!

text 2
Preapre the base's and the Exo stations' defence!!!

text 3
We have sent you reinforcements but it will take some time until they arrive.

text 4
Warning! Enemy saucer has been spotted near the colony!

text 5
Multiple enemy units detected!!!

text 6
Captain is dead. Mission aborted

text 7
Watch out!!! It's a trap!!!

text 8
Our scientific center have localized the artifacts.

text 9
Aliens' bases are destroyed!!!

text 10
Well done!!!

text 11
Colony has been destroyed. Mission aborted.

text 12
Captain had been healed and reached the base!!!

text 13
Exo stations activated: 1/9

text 14
Exo stations activated: 2/9

text 15
Exo stations activated: 3/9

text 16
Exo stations activated: 4/9

text 17
Exo stations activated: 5/9

text 18
Exo stations activated: 6/9

text 19
Exo stations activated: 7/9

text 20
Exo stations activated: 8/9

text 21
Exo stations activated: 9/9

text 22
Exo stations activated: 0/9

text 23
Enemy transmitters are still working. Mission aborted!!!

text 24
Reinforcements have arrived!!!

text 25
Now destroy these damn alien bases!!!

text 26
Reinforcements are in a half of their way.

