text 1
Welcome to the Centauri Alpha region.

text 2
It is a Ternox's major point.

text 3
Complete annihilation is necessary.

text 4
Warning! Enemy saucer has been spotted near the colony!

text 5
Active volcano has been localized near the base!!!

text 6
Captain is dead. Mission aborted

text 7
You will be demoted!

text 8
Our scientists have localized the artifacts.

text 9
All Aliens' bases are destroyed!!!

text 10
Well done!!!

text 11
Colony has been destroyed. Mission aborted.

text 12
Captain had been healed and reached the base!!!

