text 1
Find the artifact and destroy enemy bases!!!

text 2
Take any Petra-7 vent to gain reinforcements.

text 3
You were too slow!!!

text 4
You will be beheaded!!

text 5
Mind-Link activated!!! Reinforcements are coming!!!

text 6
Captain is dead. Mission aborted

text 7
You will be beheaded!!

text 8
Captain had been cloned and has reached the base!!!

text 9
Mission completed!!! 

text 10
You have failed!!!

text 11
Artifact has been found!!! Destroy enemy bases!!!

text 12
Destroy the Ternox's base where the has been hidden.

text 13
Artifact is lost you have failed!!!

text 14
Base destroyed!!!

