text 1
Fight off the attack

text 2
Destroy all enemy bases

text 3
Captain is dead. Mission aborted

text 4
You will be beheaded!!

text 5
Don't let the base to be revealed and-

text 6
Large enemy recon spotted on the east!!!

text 7
You may go if you find our captain

text 8
Captain had been cloned and has reached the base!!!

text 9
Rebels have been spotted in the area

text 10
Mission completed

text 11
There are too much of them, fall back!

text 12
Reinforcements are coming

text 13
Humans and the High Council have signed a pact against us!

text 14
Base destroyed!!!

