text 1
Find the ruins in which the artifact is hidden!!!

text 2
Take any Petra-7 vent to gain reinforcements

text 3
You were too slow. Marrus has already discovered the great power of the artifact

text 4
You will be beheaded!!

text 5
Artifact was moved to the Ternox's base

text 6
Captain is dead. Mission aborted

text 7
You will be beheaded!!

text 8
Captain had been cloned and has reached the base!!!

text 9
Mission completed!!! Artifact is found!!!

text 10
Mission completed!!!

text 11
There's nothing over here. Search another ruins.

text 12
Destroy the Ternox's base. The artifact is kept there.

text 13
Brozzar has been lost! You have failed!!!

text 14
Base destroyed!!!

