text 1
Destroy the enemy bases

text 2
Mission completed!!!

text 3
Captain is dead. Mission aborted

text 4
You will be beheaded!!!

text 5
Don't let the base to be discovered and-

text 6
Large enemy recon party spotted to the east!!!

text 7
You may go if you will find our captain

text 8
Captain had been cloned and has reached the base!!!

text 9
Go to the base and take care about its growth

text 10
Fighting between the humans and the High Council carries on

text 11
Prepare to defend the base!!!

text 12
The base has been localized by the enemy!!!

text 13
Humans and the High Council have signed a cease fire against us!

text 14
Base destroyed!!!

