text 1
Destroy enemies' bases and find the artifact!!!

text 2
Mission completed!!!

text 3
Captain is dead. Mission aborted

text 4
You will be beheaded!!

text 5
Don't let the base to be discovered and-

text 6
Large enemy recon spotted to the east!!!

text 7
You may pass if you find our captain

text 8
Captain has been cloned and has reached the base!!!

text 9
Mission completed!!! Artifact has been found

text 10
Mission completed

text 11
Be prepared to defend the base!!!

text 12
Reinforcements are coming

text 13
Humans and the High Council have signed a pact against us!

text 14
Base destroyed!!!

