text 1
Welcome, Brother

text 2
New orders received:

text 3
Our secret has been revealed!!!

text 4
Destroy High Council's base!!!

text 5
Good work!!!

text 6
Captain is dead. Mission aborted

text 7
You will be beheaded!!

text 8
Colony is destroyed. Mission aborted

text 9
Enemy base localized. Destroy all the buildings!!!

text 10
Mission completed!!!

text 11
Head towards the interrogation!!!

text 12
Interrogation finished!!! You've failed!!!

