text 1
Leave the underground through the exit north from here

text 2
Mission completed!!!

text 3
Captain is dead. Mission aborted

text 4
You will be beheaded!!

text 5
The rebels have send us a message:

text 6
Stop! One more step and you are done!!! Wanna go through?

text 7
We will let you pass if you find our captain

text 8
Go and find him or fight and die!!!

text 9
New orders received:

text 10
Find the rebels' commander or use the force to get through!!!

text 11
Warning! Landmines detected!

text 12
Only Gorrem can destroy the mines.

text 13
God bless freedom! Help me, and I'll clear the path!

text 14
Thank you for helping me, you may go

text 15
I will not escape without violence now!!!

