text 1
Wipe our enemies out of the planet's surface!!!

text 2
Dalgar have reached its destination and is at your disposal.

text 3
Captain is dead.

text 4
You will be beheaded!!

text 5
Attention!!! Enemy supply ship has been detected

text 6
Captain had been cloned and has reached the base!!!

text 7
Dalgar is destroyed!!!

text 8
Our defeat is inevitable!!!

text 9
Enemy supply ships has been spotted near the base!!!

text 10
Renewed eruption near the base has been spotted!!!

text 11
Enemy's drop point has been destroyed!!!

text 12
Mission completed!!! 

text 13
Artifact is lost. You have failed!!

text 14
Base destroyed!!!

