text 1
Unlock the entrance to the ancient ruins!!!

text 2
Second artifact is on its way!!!

text 3
Third artifact has reached the destination!!! 

text 4
You will be beheaded!!

text 5
Mind-Link activated!!! Reinforcements are coming!!!

text 6
Captain is dead. Mission aborted

text 7
Artifacts have been destroyed. You have failed!!!

text 8
Captain had been cloned and has reached the base!!!

text 9
Mission completed!!! 

text 10
Mission completed!!! 

text 11
Artifact has been found!!! Destroy enemy bases!!!

text 12
Destroy the Ternox's base, where the artifact has been hidden.

text 13
Artifact is lost. You have failed!!

text 14
Base destroyed!!!

