text 1
Enemy unit incoming it must be destroyed!!!

text 2
Destroy all the enemy bases

text 3
Captain is dead. Mission aborted

text 4
You will be beheaded!!

text 5
Destroy all 15 transmitters and then destroy the enemy base

text 6
Large enemy recon spotted to the east!!!

text 7
You may go if you find our captain

text 8
Captain has been cloned and has reached the base!!!

text 9
We are sending a few reinforcements from Ternox 

text 10
Mission completed!!!

text 11
All transmitters have been destroyed

text 12
Base has been localized by the enemy!!!

text 13
Humans and the High Council have signed a pact fire against us!

text 14
You were too slow!!!

